// src/components/overview/SidebarContent/Content/Inputs/SelectInput/MultipleSelectWithSearch.jsx
import React, {useEffect, useState} from "react";

// react icons
import {IoIosArrowDown} from "react-icons/io";
import {IoCheckmark} from "react-icons/io5";

const MultipleSelectWithSearch = () => {
    const [searchValue, setSearchValue] = useState("");
    const [isDropdownOpen, setIsDropdownOpen] = useState(false);
    const [selectedItems, setSelectedItems] = useState([]);

    // all options
    const options = [
        { id: 1, name: "Option 1" },
        { id: 2, name: "Option 2" },
        { id: 3, name: "Option 3" },
        { id: 4, name: "Option 4" },
        { id: 5, name: "Option 5" },
    ];

    // filtered items
    const filteredItems = options.filter((item) =>
        item.name.toLowerCase().includes(searchValue.toLowerCase())
    );

    // checking is the item is selected or not
    const isSelected = (item) => {
        return selectedItems.some((selectedItem) => selectedItem.id === item.id);
    };

    // the select toggle
    const toggleSelect = (item) => {
        if (isSelected(item)) {
            setSelectedItems(
                selectedItems.filter((selectedItem) => selectedItem.id !== item.id)
            );
        } else {
            setSelectedItems([...selectedItems, item]);
        }
    };

    // outside click to off the dropdown
    useEffect(() => {
        const handleClickOutside = (event) => {
            if (event.target.closest(".custom-select")) return;
            setTimeout(() => {
                setIsDropdownOpen(false);
            }, 200);
        };
        document.addEventListener("mousedown", handleClickOutside);
        return () => document.removeEventListener("mousedown", handleClickOutside);
    }, []);

    return (
        <div className="p-8 mb-4 flex items-center flex-col gap-5 justify-center">
            <div className="relative custom-select w-[80%]">
                {/* Input field with search functionality */}
                <input
                    type="text"
                    placeholder="Search.."
                    value={searchValue}
                    onChange={(e) => setSearchValue(e.target.value)}
                    onFocus={() => setIsDropdownOpen(true)}
                    className={`w-full border dark:bg-transparent dark:border-slate-600 dark:text-[#abc2d3] border-gray-300 rounded-md px-3 py-2 focus:outline-none`}
                />

                <IoIosArrowDown
                    className={`${
                        isDropdownOpen ? "rotate-[180deg]" : "rotate-0"
                    } transition-all duration-300 text-[1.3rem] absolute top-[50%] transform translate-y-[-50%] right-3 text-gray-500`}
                />

                {/* Dropdown menu */}
                {isDropdownOpen && (
                    <div
                        className="absolute left-0 dark:border-slate-700 dark:bg-slate-800 w-full mt-1 border border-gray-200 rounded-md bg-white shadow-lg z-20">
                        <div className="w-full overflow-auto">
                            {filteredItems.map((item) => (
                                <p
                                    key={item.id}
                                    onClick={() => toggleSelect(item)}
                                    className="cursor-pointer px-3 dark:text-[#abc2d3] dark:hover:bg-slate-900/40 py-2 flex items-center hover:bg-gray-200"
                                >
                                    <IoCheckmark
                                        className={`${
                                            isSelected(item)
                                                ? "scale-[1] opacity-100"
                                                : "scale-[0.5] opacity-0"
                                        } mr-2 transition-all text-[1.3rem] duration-300`}
                                    />
                                    {item.name}
                                </p>
                            ))}

                            {filteredItems?.length === 0 && (
                                <p className="text-center dark:text-[#abc2d3] text-[0.9rem] text-text py-8">
                                    No search found!
                                </p>
                            )}
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default MultipleSelectWithSearch;

// src/components/overview/SidebarContent/Content/Inputs/SelectBox/MultipleSelectWithSearch.vue
<script setup>
import {computed, onBeforeUnmount, onMounted, ref} from "vue";
import {Icon} from "@iconify/vue";

const searchValue = ref("");
const isDropdownOpen = ref(false);
const selectedItems = ref([]);

const options = ref([
  {id: 1, name: "Option 1"},
  {id: 2, name: "Option 2"},
  {id: 3, name: "Option 3"},
  {id: 4, name: "Option 4"},
  {id: 5, name: "Option 5"},
]);

const filteredItems = computed(() =>
    options.value.filter((item) =>
        item.name.toLowerCase().includes(searchValue.value.toLowerCase())
    )
);

const isSelected = (item) =>
    selectedItems.value.some((selected) => selected.id === item.id);

const toggleSelect = (item) => {
  if (isSelected(item)) {
    selectedItems.value = selectedItems.value.filter(
        (selected) => selected.id !== item.id
    );
  } else {
    selectedItems.value.push(item);
  }
};

const handleClickOutside = (event) => {
  if (event.target.closest(".custom-select")) return;
  setTimeout(() => {
    isDropdownOpen.value = false;
  }, 200);
};

onMounted(() => {
  document.addEventListener("mousedown", handleClickOutside);
});
onBeforeUnmount(() => {
  document.removeEventListener("mousedown", handleClickOutside);
});
</script>

<template>
  <div class="relative custom-select w-full 1024px:w-[60%]">
    <input
        type="text"
        placeholder="Search.."
        v-model="searchValue"
        @focus="isDropdownOpen = true"
        class="w-full border dark:bg-transparent dark:border-slate-600 dark:text-[#abc2d3] border-gray-300 rounded-md px-3 py-2 focus:outline-none"
    />

    <Icon icon="proicons:chevron-down"
          :class="[
            'transition-all duration-300 text-[1.3rem] absolute top-[50%] transform translate-y-[-50%] right-3 text-gray-500',
            isDropdownOpen ? 'rotate-[180deg]' : 'rotate-0'
            ]"
    />

    <Transition
        enter-active-class="transition-all duration-200 ease-out"
        enter-from-class="opacity-0 -translate-y-1"
        enter-to-class="opacity-100 translate-y-0"
        leave-active-class="transition-all duration-150 ease-in"
        leave-from-class="opacity-100 translate-y-0"
        leave-to-class="opacity-0 -translate-y-2"
    >
      <div
          v-if="isDropdownOpen"
          class="absolute left-0 dark:border-slate-700 p-1 dark:bg-slate-800 w-full mt-1 border border-gray-200 rounded-md bg-white shadow-lg z-20"
      >
        <div class="w-full overflow-auto">
          <p
              v-for="item in filteredItems"
              :key="item.id"
              @click="toggleSelect(item)"
              class="cursor-pointer px-3 rounded-lg dark:text-[#abc2d3] dark:hover:bg-slate-900/40 py-2 flex items-center hover:bg-gray-200"
          >
            <Icon icon="weui:done-outlined"
                  :class="[
                        'mr-2 transition-all text-[1.3rem] duration-300',
                        isSelected(item)
                        ? 'scale-[1] opacity-100'
                        : 'scale-[0.5] opacity-0'
                        ]"
            />
            {{ item.name }}
          </p>

          <p
              v-if="filteredItems.length === 0"
              class="text-center dark:text-[#abc2d3] text-[0.9rem] text-text py-8"
          >
            No search found!
          </p>
        </div>
      </div>
    </Transition>
  </div>
</template>
