// src/Shared/CookieModal.jsx
import React, {useEffect} from "react";
 
const CookieModal = ({isModalOpen, setisModalOpen}) => {

    useEffect(() => {
        if (!localStorage.getItem("zenUICookiesAccepted")) {
            setTimeout(() => {
                setisModalOpen(true)
            }, 6000)
        }
    }, [])

    const acceptCookie = () => {
        localStorage.setItem("zenUICookiesAccepted", "true");
        setisModalOpen(false)
    }

    const cancelCookie = () => {
        localStorage.setItem("zenUICookiesAccepted", "true");
        setisModalOpen(false)
    }

    return (
        <>
            <div
                className={`${
                    isModalOpen
                        ? " translate-y-[0px] opacity-100"
                        : " translate-y-[200px] opacity-0"
                } w-[95%] 1024px:w-[70%] bg-white transition-all fixed boxShadow rounded-md duration-300 mx-auto mt-8 bottom-3 left-[50%] z-[2000] dark:bg-slate-800 transform translate-x-[-50%]`}
            >
                <div
                    className="flex items-center gap-[20px] flex-col 640px:flex-row justify-between py-[20px] px-[30px]">
                    <p className={`text-[0.9rem] 1024px:w-[70%] dark:text-darkTextColor`}>
                        We use cookies to improve your experience, personalize content, and analyze traffic. By clicking
                        "Accept" you agree to our cookie use. For details, see our <a href="/privacy-policy"
                                                                                      className='text-[#0FABCA] underline'>Privacy
                        Policy</a>.
                    </p>

                    <div className="flex items-end justify-end gap-4 w-full 1024px:w-[20%]">
                        <button
                            className="py-2 w-full px-4 rounded-md outline-none bg-[#0FABCA] text-[#fff]"
                            onClick={acceptCookie}
                        >
                            Accept
                        </button>
                        <button
                            className={`py-2 w-full px-4 text-gray-500 dark:text-darkTextColor dark:border-slate-700 border border-gray-200 rounded-md outline-none`}
                            onClick={cancelCookie}
                        >
                            Decline
                        </button>
                    </div>
                </div>
            </div>
        </>
    );
};

export default CookieModal;

// src/Shared/CookieModal.vue
<script setup>
import {onMounted} from "vue";

const props = defineProps({
  isModalOpen: {
    type: Boolean,
    required: true,
  },
});

const emit = defineEmits(["update:isModalOpen"]);

onMounted(() => {
  if (!localStorage.getItem("zenUI-vCookiesAccepted")) {
    setTimeout(() => {
      emit("update:isModalOpen", true);
    }, 6000);
  }
});

const acceptCookie = () => {
  localStorage.setItem("zenUI-vCookiesAccepted", "true");
  emit("update:isModalOpen", false);
};

const cancelCookie = () => {
  localStorage.setItem("zenUI-vCookiesAccepted", "true");
  emit("update:isModalOpen", false);
};
</script>

<template>
  <div
      :class="[
      isModalOpen 
        ? 'translate-y-[0px] opacity-100'
        : 'translate-y-[200px] opacity-0',
      'bg-brandColor transition-all fixed boxShadow rounded-md duration-300 mx-auto mt-8 bottom-3 left-[15px] z-[2000] transform'
    ]"
  >
    <div
        class="flex items-center gap-[20px] 1024px:gap-[50px] flex-col 640px:flex-row justify-between py-[20px] px-[30px]">
      <p class="text-[0.9rem] 1024px:w-[70%] text-white">
        We use cookies to make your experience better. <br/> By accepting, you agree to our
        <a href="/privacy-policy" class='text-white font-bold underline'>Privacy
          Policy</a>.
      </p>

      <div class="flex items-end justify-end gap-4 w-full 1024px:w-[20%]">
        <button
            class="py-2 w-full px-4 rounded-md outline-none hover:bg-white/90 bg-white"
            @click="acceptCookie"
        >
          Accept
        </button>
        <button
            class="py-2 w-full px-4 hover:bg-emerald-500 text-white border border-gray-200 rounded-md outline-none"
            @click="cancelCookie"
        >
          Decline
        </button>
      </div>
    </div>
  </div>
</template>
